### ISSUE TITLE
Decode Function Doesn't Work

### ISSUE THREAD

**Issue by Mhankk** [systoms/zoeeyguard#1]
Code to Run : 
```php
$php = '<?php echo 11; ?>';
$code_len = strlen($php);
$code = (new Zoeey())->encode($php,"123456789");
echo '加密后代码: |',$code,"|\n";
$code = (new Zoeey())->decode($code,"123456789");
echo '解密后代码: |',$code,"|\n";
```

Given Result :
`Encrypted Code: |vlkbr/afo0OMQjHpZ8Xdv+4=| Decrypted Code: ||` 

It doesn't show as an error but the `decode()` show nothing.

im also trying to do something like this 
```php
$text = "vlkbr/afo0OMQjHpZ8Xdv+4=";
$result = (new Zoeey())->decode($text,"123456789");
echo 'Decrypted Code: |',$result,"|\n";
```
and it still doesnt work.
can someone help me? plz

fwd : @systoms

**Comment by systoms** [comment]
已经修复了
